### ISSUE TITLE
README在线阅读链接

### ISSUE THREAD

**Issue by hyzgh** [gdut-yy/Clean-Architecture-zh#2]
现在点击README的在线阅读链接，跳转到的版本是英文的，需要手动切换到中文版本。因为该仓库是中文译本的仓库，所以把链接替换成http://gdut_yy.gitee.io/doc-cleanarch/zh 会不会更合适:smile:

**Comment by gdut-yy** [comment]
@hyzgh 感谢你的指出，这个短期内的确是个问题，这个项目的目标是做成像 https://github.com/gdut-yy/Domain-Driven-Design-zh 项目一样的效果，即把中文翻译嵌入到英文文本当中。

当前拉出 /zh/ 目录主要是为了勘误，因为 /zh/ 的文本内容主要来源于 OCR 识别以及人工校对。当前还存在一些问题：如标点符号大小写、错别字、没有配图等。暂不适合作为阅读主分支，望理解，谢谢！^_^~

**Comment by gdut-yy** [comment]
特性已开发完毕，关闭 issue
