### ISSUE TITLE
翻译改进

### ISSUE THREAD

**Issue by hyzgh** [gdut-yy/Clean-Architecture-zh#3]
http://gdut_yy.gitee.io/doc-cleanarch/ch3.html
Probably not现在翻译成“没有了”，翻译成“可能没有了”会不会更恰当些？

**Comment by hyzgh** [comment]
https://gdut_yy.gitee.io/doc-cleanarch/ch5.html#inheritance-%E7%BB%A7%E6%89%BF

1. Inheritance is simply the redeclaration of a group of variables and functions within an enclosing scope. 
简而言之，继承的主要作用是让我们可以在某个作用域内对外部定义的某一组变量与函数进行覆盖。
问题：翻译读起来怪怪的，是出错了吗？

2. Constructors of derivatives simply load their versions of those functions into the vtable of the object being created.
我们对虚函数的每次调用都要先查询这个表，其衍生类的构造函数负责将该衍生类的虚的数地址加载到整个对象的 vtable 中。
问题：同上

3. The problem with explicitly using pointers to functions to create polymorphic behavior is that pointers to functions are dangerous.
用函数抬针显式实现彩态的问题就在于函数指针的危险性。
问题：同上

4. 插件式架构就是为了支持这种 IO 不相关性而发明的，它几乎在随后的所有系统中都有应用。但即使多态有如此多优点，大部分程序员还是没有将插件特性引入他们自己的程序中，因为函数指针实在是太危险了。
问题：没有引用。

5. OO allows the plugin architecture to be used anywhere, for anything.
问题：没有翻译。

6. Imagine what software was like before a safe and convenient mechanism for polymorphism was available. In the typical calling tree, main functions called high-level functions, which called mid-level functions, which called low-level functions. In that calling tree, however, source code dependencies inexorably followed the flow of control (Figure 5.1).
问题：缺少图片。

**Comment by gdut-yy** [comment]
fixed 0-2-3-4-5-6 by commitId f493420960866f47984e2d97053476d607050bde

1 保留意见，或者请提供更好的翻译版本

**Comment by hyzgh** [comment]
3 "用函数抬针显式实现多态的问题就在于函数指针的危险性"中的"抬针"应该是"指针"？

**Comment by gdut-yy** [comment]
@hyzgh 是的，已修正。兄弟 tql

**Comment by hyzgh** [comment]
http://gdut_yy.gitee.io/doc-cleanarch/ch6.html
7. The answer to that question is affirmative, if you have infinite storage and infinite processor speed.
问题：翻译可能有误
8. The immutable components communicate with one or more other components that are not purely functional, and allow for the state of variables to be mutated (Figure 6.1).
问题：翻译可能有误
9. Nowadays it is common for processors to execute billions of instructions per second and to have billions of bytes of RAM. 
问题：翻译可能有误

http://gdut_yy.gitee.io/doc-cleanarch/part3.html
10. They are applied just above the level of the code and help to define the kinds of software structures used within modules and components. 
问题：翻译可能有误，"software structures  used within modules and components"的意思应该是"在模块和组件中使用的软件架构"

**Comment by gdut-yy** [comment]
7. The answer to that question is affirmative, if you have infinite storage and infinite processor speed. Lacking those infinite resources, the answer is a bit more nuanced. Yes, immutability can be practicable, if certain compromises are made.
如果我们能忽略存储器与处理器在速度上的限制，那么答案是肯定的。否则的话，不可变性只有在一定情况下是可行的。
-- 与官方翻译版本一致。

8. The immutable components communicate with one or more other components that are not purely functional, and allow for the state of variables to be mutated (Figure 6.1).
这些不可变的组件将通过与一个或多个非函数式组件通信的方式来修改变量状态（参见图 6.1）。
-- 与官方翻译版本一致。

9. The limits of storage and processing power have been rapidly receding from view. Nowadays it is common for processors to execute billions of instructions per second and to have billions of bytes of RAM. The more memory we have, and the faster our machines are, the less we need mutable state.
-- 修改为：随着存储和处理能力的大幅进步，现在拥有每秒可以执行数十亿条指令的处理器，以及数十亿字节内存的计算机已经很常见了。而内存越大，处理速度越快，我们对可变状态的依赖就会越少。

10. They are applied just above the level of the code and help to define the kinds of software structures used within modules and components.
SOLID 原则应该直接紧贴于具体的代码逻辑之上，这些原则是用来帮助我们定义软件架构中的组件和模块的。
-- 与官方翻译版本一致。

---

个人倾向于官翻版本（Broadview 发行版），因为结合 part3 上下文，主要讨论的是如何设计组件和模块，组件和模块是“砖头”，软件架构是“楼/建筑物”。你认为呢？欢迎交流，谢谢！~

**Comment by hyzgh** [comment]
7. The answer to that question is affirmative, if you have infinite storage and infinite processor speed. 
可能更合适的翻译：如果我们能忽略存储器在大小上的限制以及处理器在速度上的限制，那么答案是肯定的。
9. 同意。
10. 这个我再想想~
---
官翻版本也不一定正确哈，我认为现在译文总体上是准确的，但是部分地方可以改进~
另外，官翻版本在哪里可以看到呢，能否麻烦给个链接 😃

**Comment by gdut-yy** [comment]
> 官翻版本也不一定正确哈，我认为现在译文总体上是准确的，但是部分地方可以改进~

是的，这就是我创建此 repo 并放上中英双语的原因。通过中英双语版本，基本不会偏离作者原意了。

官翻版本已出版：https://item.jd.com/12447192.html
