### ISSUE TITLE
错字纠正

### ISSUE THREAD

**Issue by nimoc** [gdut-yy/Clean-Architecture-zh#5]
请全局搜索这几句话

并不像如今的继昼：样便利易用
便圈外血的代码只能看见部分
量的话都不对能发工
是一个设订原则，即确保一个
将大型函数亜构成小函
员这样 做实际上就  // 这样做之间多了一个空格)
响到 C 00 团队所依 // 是COO

**Comment by gdut-yy** [comment]
并不像如今的继昼：样便利易用 => 并不像如今的继承这样便利易用
便圈外血的代码只能看见部分 => 使圈外面的代码只能看见部分
量的话都不对能发工 => 量的话都不可能发生
是一个设订原则，即确保一个 => 是一个设计原则，即确保一个
将大型函数亜构成小函 => 将大型函数重构成小函
员这样 做实际上就 => 员这样做实际上就
响到 C 00 团队所依 => 响到 COO 团队所依

**Comment by gdut-yy** [comment]
fixed by d386a04f11a932b48b828dc2ca1e10a9513a4344
